### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by mcpll** [mattheu/modular-page-builder#12] opened 2015-12-21 11:38 UTC
Hello,
I'm trying to manage this plugin, once installed upon activation me right back this error:

Fatal error: Call to undefined function ModularPageBuilder\register_api_field() in C:\xampp\htdocs\test\wp-content\plugins\modular-page-builder-dev\inc\class-builder-post-meta.php on line 104

**Comment by mattheu** [comment] 2015-12-21 12:24
Looks like I'm assuming the rest API plugin is installed - although this isn't actually requied. I'll fix Asap - for now you can just comment this code out.

**Comment by mcpll** [comment] 2015-12-21 13:13
I'm trying to active the wp api plugin but the error persist, Did you mention the plugin wp - api?

**Comment by roborourke** [comment] 2016-05-02 13:01
@mcpll it's this plugin: http://v2.wp-api.org/ - you may find the issue is resolved with the latest WP versions that include the REST API framework too.

**Closed as completed** 2016-05-03 23:05 UTC
